name: Build on linux

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with: 
          ocaml-compiler: 5

      - name: Install depedencies
        run: opam install . --deps-only --with-test

      - name: Format
        run: opam exec -- dune fmt

      - name: Build
        run: opam exec -- dune build @check @all

